# Generated by Django 4.2.6 on 2026-06-19 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DCPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du pack')),
                ('dc_amount', models.IntegerField(help_text='Nombre de DC inclus dans ce pack', verbose_name='Montant DC')),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix (€)')),
                ('stripe_price_id', models.CharField(blank=True, help_text='ID du prix Stripe (price_xxx). Laisser vide si Stripe non configuré.', max_length=255, verbose_name='ID prix Stripe')),
                ('is_popular', models.BooleanField(default=False, help_text="Affiche un badge 'Populaire'", verbose_name='Populaire')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Pack DC',
                'verbose_name_plural': 'Packs DC',
                'ordering': ['order', 'price_eur'],
            },
        ),
        migrations.CreateModel(
            name='DCPackOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dc_amount', models.IntegerField(verbose_name='DC achetés')),
                ('price_paid_eur', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Prix payé (€)')),
                ('stripe_session_id', models.CharField(max_length=255, unique=True, verbose_name='ID session Stripe')),
                ('stripe_payment_intent', models.CharField(blank=True, max_length=255, verbose_name='Payment Intent Stripe')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de commande')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
                ('pack', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.dcpack', verbose_name='Pack acheté')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_pack_orders', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Commande DC',
                'verbose_name_plural': 'Commandes DC',
                'ordering': ['-created_at'],
            },
        ),
    ]
