# Generated by Django 4.2.6 on 2026-06-20 20:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dcpackorder',
            name='admin_notes',
            field=models.TextField(blank=True, verbose_name="Notes de l'administrateur"),
        ),
        migrations.AddField(
            model_name='dcpackorder',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('orange_money', 'Orange Money'), ('wave', 'Wave'), ('bank_transfer', 'Virement bancaire'), ('cash', 'Espèces'), ('recharge_code', 'Code de recharge')], default='stripe', max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='dcpackorder',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Référence de transaction (Orange Money, Wave, etc.)'),
        ),
        migrations.AlterField(
            model_name='dcpackorder',
            name='status',
            field=models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='dcpackorder',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, unique=True, verbose_name='ID session Stripe'),
        ),
        migrations.CreateModel(
            name='RechargeCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Code de recharge')),
                ('dc_amount', models.IntegerField(verbose_name='Montant DC')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('used', 'Utilisé'), ('expired', 'Expiré'), ('cancelled', 'Annulé')], default='active', max_length=20)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'expiration")),
                ('notes', models.TextField(blank=True, help_text='Notes sur ce code de recharge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recharge_codes', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_recharge_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Code de recharge',
                'verbose_name_plural': 'Codes de recharge',
                'ordering': ['-created_at'],
            },
        ),
    ]
