# Generated by Django 4.2.6 on 2026-06-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_dcpackorder_admin_notes_dcpackorder_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dcpackorder',
            name='stripe_session_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID session Stripe'),
        ),
    ]
