# Generated by Django 4.2.6 on 2026-06-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_dcpackorder_stripe_session_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dcpack',
            options={'ordering': ['order', 'price_cfa'], 'verbose_name': 'Pack DC', 'verbose_name_plural': 'Packs DC'},
        ),
        migrations.AddField(
            model_name='dcpack',
            name='price_cfa',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Prix (FCFA)'),
        ),
        migrations.AddField(
            model_name='dcpackorder',
            name='price_paid_cfa',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Prix payé (FCFA)'),
        ),
        migrations.AlterField(
            model_name='dcpack',
            name='price_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Prix (€) - OBSOLETE'),
        ),
        migrations.AlterField(
            model_name='dcpackorder',
            name='price_paid_eur',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Prix payé (€) - OBSOLETE'),
        ),
    ]
