# Generated by Django 4.2 on 2026-06-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_dcpack_options_dcpack_price_cfa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dcpack',
            name='price_eur',
        ),
        migrations.RemoveField(
            model_name='dcpackorder',
            name='price_paid_eur',
        ),
    ]
