# Generated by Django 4.2 on 2026-06-30 23:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_type', models.CharField(choices=[('school', 'Licence École'), ('university', 'Licence Université'), ('enterprise', 'Licence Entreprise'), ('custom', 'Licence Personnalisée')], max_length=20, verbose_name='Type de licence')),
                ('license_key', models.CharField(max_length=100, unique=True, verbose_name='Clé de licence')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la licence')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('price_cfa', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Prix (FCFA)')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='yearly', max_length=20, verbose_name='Cycle de facturation')),
                ('max_students', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max étudiants')),
                ('max_teachers', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Max enseignants')),
                ('max_courses', models.IntegerField(blank=True, null=True, verbose_name='Max cours')),
                ('max_exams', models.IntegerField(blank=True, null=True, verbose_name='Max examens')),
                ('has_certificates', models.BooleanField(default=True, verbose_name='Certificats')),
                ('has_analytics', models.BooleanField(default=True, verbose_name='Analytics')),
                ('has_api_access', models.BooleanField(default=False, verbose_name='Accès API')),
                ('has_custom_branding', models.BooleanField(default=False, verbose_name='Branding personnalisé')),
                ('has_priority_support', models.BooleanField(default=True, verbose_name='Support prioritaire')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('expired', 'Expiré'), ('suspended', 'Suspendu'), ('cancelled', 'Annulé')], default='active', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(verbose_name='Date de fin')),
                ('current_students', models.IntegerField(default=0, verbose_name='Étudiants actuels')),
                ('current_teachers', models.IntegerField(default=0, verbose_name='Enseignants actuels')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Licence B2B',
                'verbose_name_plural': 'Licences B2B',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='B2BPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name="Nom de l'organisation")),
                ('partner_type', models.CharField(choices=[('school', 'École'), ('university', 'Université'), ('company', 'Entreprise'), ('ngo', 'ONG'), ('government', 'Gouvernement'), ('other', 'Autre')], max_length=20, verbose_name='Type de partenaire')),
                ('contact_person', models.CharField(max_length=200, verbose_name='Personne de contact')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('address', models.TextField(blank=True, verbose_name='Adresse')),
                ('tax_id', models.CharField(blank=True, max_length=50, verbose_name='Numéro fiscal')),
                ('registration_number', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'enregistrement")),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('active', 'Actif'), ('suspended', 'Suspendu'), ('inactive', 'Inactif')], default='pending', max_length=20, verbose_name='Statut')),
                ('contract_start_date', models.DateField(blank=True, null=True, verbose_name='Date début contrat')),
                ('contract_end_date', models.DateField(blank=True, null=True, verbose_name='Date fin contrat')),
                ('contract_terms', models.TextField(blank=True, verbose_name='Conditions du contrat')),
                ('billing_email', models.EmailField(blank=True, max_length=254, verbose_name='Email de facturation')),
                ('billing_address', models.TextField(blank=True, verbose_name='Adresse de facturation')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': 'Partenaire B2B',
                'verbose_name_plural': 'Partenaires B2B',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='B2BTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('license_purchase', 'Achat de licence'), ('license_renewal', 'Renouvellement de licence'), ('license_upgrade', 'Upgrade de licence'), ('add_seats', 'Ajout de places'), ('custom_service', 'Service personnalisé')], max_length=30, verbose_name='Type de transaction')),
                ('amount_cfa', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Montant (FCFA)')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='Méthode de paiement')),
                ('payment_reference', models.CharField(blank=True, max_length=200, verbose_name='Référence de paiement')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Complété'), ('failed', 'Échoué'), ('refunded', 'Remboursé')], default='pending', max_length=20, verbose_name='Statut')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Numéro de facture')),
                ('invoice_sent', models.BooleanField(default=False, verbose_name='Facture envoyée')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
                ('license', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='b2b.b2blicense', verbose_name='Licence')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='b2b.b2bpartner', verbose_name='Partenaire')),
            ],
            options={
                'verbose_name': 'Transaction B2B',
                'verbose_name_plural': 'Transactions B2B',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='b2blicense',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='b2b.b2bpartner', verbose_name='Partenaire'),
        ),
        migrations.CreateModel(
            name='B2BUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('teacher', 'Enseignant'), ('student', 'Étudiant')], max_length=20, verbose_name='Rôle')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='b2b_users_added', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('license', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='b2b.b2blicense', verbose_name='Licence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b2b_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Utilisateur B2B',
                'verbose_name_plural': 'Utilisateurs B2B',
                'ordering': ['-added_at'],
                'unique_together': {('license', 'user')},
            },
        ),
    ]
