# Generated by Django 4.2.6 on 2026-06-18 00:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0002_alter_subject_options_alter_userskill_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_activities', models.IntegerField(default=0, verbose_name='Total activités')),
                ('activities_this_week', models.IntegerField(default=0, verbose_name='Activités cette semaine')),
                ('activities_this_month', models.IntegerField(default=0, verbose_name='Activités ce mois')),
                ('total_exams_taken', models.IntegerField(default=0, verbose_name='Total examens passés')),
                ('exams_passed', models.IntegerField(default=0, verbose_name='Examens réussis')),
                ('exams_failed', models.IntegerField(default=0, verbose_name='Examens échoués')),
                ('average_exam_score', models.IntegerField(blank=True, null=True, verbose_name='Score moyen examen')),
                ('courses_completed', models.IntegerField(default=0, verbose_name='Cours complétés')),
                ('tds_completed', models.IntegerField(default=0, verbose_name='TDs complétés')),
                ('preferred_content_type', models.CharField(blank=True, max_length=20, verbose_name='Type de contenu préféré')),
                ('total_time_spent_minutes', models.IntegerField(default=0, verbose_name='Temps total passé (minutes)')),
                ('average_session_duration_minutes', models.IntegerField(blank=True, null=True, verbose_name='Durée moyenne session (minutes)')),
                ('skill_areas_improved', models.IntegerField(default=0, verbose_name='Zones de compétence améliorées')),
                ('skill_areas_declined', models.IntegerField(default=0, verbose_name='Zones de compétence en déclin')),
                ('last_calculated_at', models.DateTimeField(auto_now=True, verbose_name='Dernier calcul')),
                ('most_active_subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.subject', verbose_name='Matière la plus active')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Analytics utilisateur',
                'verbose_name_plural': 'Analytics utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'Connexion'), ('logout', 'Déconnexion'), ('exam_start', 'Début examen'), ('exam_complete', 'Fin examen'), ('course_start', 'Début cours'), ('course_complete', 'Fin cours'), ('td_start', 'Début TD'), ('td_complete', 'Fin TD'), ('badge_earned', 'Badge obtenu'), ('level_up', 'Niveau supérieur'), ('recommendation_view', 'Vue recommandation'), ('leaderboard_view', 'Vue classement'), ('content_submit', 'Soumission contenu'), ('content_approved', 'Contenu approuvé')], max_length=50, verbose_name="Type d'activité")),
                ('related_exam_id', models.IntegerField(blank=True, null=True, verbose_name='ID examen lié')),
                ('related_course_id', models.IntegerField(blank=True, null=True, verbose_name='ID cours lié')),
                ('related_td_id', models.IntegerField(blank=True, null=True, verbose_name='ID TD lié')),
                ('related_badge_id', models.IntegerField(blank=True, null=True, verbose_name='ID badge lié')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Données contextuelles supplémentaires', verbose_name='Contexte')),
                ('session_duration_seconds', models.IntegerField(blank=True, help_text='Durée de la session en secondes', null=True, verbose_name='Durée session (secondes)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'activité")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Activité utilisateur',
                'verbose_name_plural': 'Activités utilisateurs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='analytics_u_user_id_39836b_idx'), models.Index(fields=['activity_type', '-created_at'], name='analytics_u_activit_7e1dbf_idx')],
            },
        ),
    ]
