# Generated by Django 4.2 on 2026-07-01 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='ID Session')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='Heure de début')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Durée (secondes)')),
                ('page_views_count', models.IntegerField(default=0, verbose_name='Nombre de vues')),
                ('unique_pages_count', models.IntegerField(default=0, verbose_name='Pages uniques')),
                ('entry_page', models.CharField(blank=True, max_length=500, verbose_name="Page d'entrée")),
                ('exit_page', models.CharField(blank=True, max_length=500, verbose_name='Page de sortie')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name="Type d'appareil")),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('journey_path', models.JSONField(blank=True, default=list, verbose_name='Parcours')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Session terminée')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Session utilisateur',
                'verbose_name_plural': 'Sessions utilisateurs',
                'ordering': ['-start_time'],
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, verbose_name='ID Session')),
                ('url', models.CharField(max_length=500, verbose_name='URL')),
                ('page_title', models.CharField(blank=True, max_length=255, verbose_name='Titre de la page')),
                ('referrer', models.URLField(blank=True, verbose_name='Référant')),
                ('duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='Durée (secondes)')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('device_type', models.CharField(blank=True, max_length=50, verbose_name="Type d'appareil")),
                ('browser', models.CharField(blank=True, max_length=50, verbose_name='Navigateur')),
                ('os', models.CharField(blank=True, max_length=50, verbose_name="Système d'exploitation")),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Pays')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de la vue')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Vue de page',
                'verbose_name_plural': 'Vues de pages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=255, verbose_name='ID Session')),
                ('page_url', models.CharField(max_length=500, verbose_name='URL de la page')),
                ('element_id', models.CharField(blank=True, max_length=255, verbose_name="ID de l'élément")),
                ('element_class', models.CharField(blank=True, max_length=255, verbose_name="Classe de l'élément")),
                ('element_tag', models.CharField(blank=True, max_length=50, verbose_name="Tag de l'élément")),
                ('element_text', models.CharField(blank=True, max_length=255, verbose_name="Texte de l'élément")),
                ('href', models.URLField(blank=True, verbose_name='Lien (href)')),
                ('x_position', models.IntegerField(blank=True, null=True, verbose_name='Position X')),
                ('y_position', models.IntegerField(blank=True, null=True, verbose_name='Position Y')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du clic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='click_events', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Événement de clic',
                'verbose_name_plural': 'Événements de clics',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['session_id'], name='analytics_u_session_1131bd_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['user', '-start_time'], name='analytics_u_user_id_0cfd6b_idx'),
        ),
        migrations.AddIndex(
            model_name='usersession',
            index=models.Index(fields=['-start_time'], name='analytics_u_start_t_1aa761_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['session_id', '-created_at'], name='analytics_p_session_5811c4_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['user', '-created_at'], name='analytics_p_user_id_c122b8_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['url'], name='analytics_p_url_b57c0b_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['-created_at'], name='analytics_p_created_44ec6b_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['session_id', '-created_at'], name='analytics_c_session_be4e06_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['user', '-created_at'], name='analytics_c_user_id_d97664_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['page_url'], name='analytics_c_page_ur_9cdf76_idx'),
        ),
        migrations.AddIndex(
            model_name='clickevent',
            index=models.Index(fields=['-created_at'], name='analytics_c_created_c54993_idx'),
        ),
    ]
