# Generated by Django 4.2 on 2026-07-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_usersession_pageview_clickevent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Code Pays'),
        ),
        migrations.AddField(
            model_name='usersession',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Code Pays'),
        ),
    ]
