# Generated by Django 4.2 on 2026-07-05 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0014_examsession_dc_earned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0004_skill'),
        ('analytics', '0003_pageview_country_code_usersession_country_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='Score')),
                ('xp_earned', models.IntegerField(default=0, verbose_name='XP gagné')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date de l'examen")),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_results', to='exams.exam', verbose_name='Examen')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Résultat d'examen",
                'verbose_name_plural': "Résultats d'examens",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=1, verbose_name='Niveau')),
                ('progress', models.IntegerField(default=0, verbose_name='Progression')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='skills.skill', verbose_name='Compétence')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Compétence utilisateur',
                'verbose_name_plural': 'Compétences utilisateurs',
                'ordering': ['-level'],
                'unique_together': {('user', 'skill')},
            },
        ),
    ]
