# Generated by Django 4.2.6 on 2026-05-14 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0002_alter_subject_options_alter_userskill_options_and_more'),
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['-created_at'], 'verbose_name': 'Contenu communautaire', 'verbose_name_plural': 'Contenus communautaires'},
        ),
        migrations.AlterModelOptions(
            name='moderationrule',
            options={'ordering': ['name'], 'verbose_name': 'Règle de modération', 'verbose_name_plural': 'Règles de modération'},
        ),
        migrations.AlterField(
            model_name='content',
            name='author',
            field=models.ForeignKey(help_text='Utilisateur qui a soumis le contenu', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_content', to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(help_text='Contenu en texte ou HTML', verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content_type',
            field=models.CharField(choices=[('course', 'Cours'), ('td', 'TD (Travaux Dirigés)'), ('corrected_td', 'TD corrigé')], help_text='Type de contenu soumis', max_length=20, verbose_name='Type de contenu'),
        ),
        migrations.AlterField(
            model_name='content',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='content',
            name='description',
            field=models.TextField(blank=True, help_text='Description courte du contenu', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='content',
            name='moderated_at',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle le contenu a été modéré', null=True, verbose_name='Date de modération'),
        ),
        migrations.AlterField(
            model_name='content',
            name='moderated_by',
            field=models.ForeignKey(blank=True, help_text='Modérateur qui a approuvé/rejeté le contenu', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_content', to=settings.AUTH_USER_MODEL, verbose_name='Modéré par'),
        ),
        migrations.AlterField(
            model_name='content',
            name='moderation_notes',
            field=models.TextField(blank=True, help_text='Notes du modérateur expliquant la décision', verbose_name='Notes de modération'),
        ),
        migrations.AlterField(
            model_name='content',
            name='moderation_rule',
            field=models.ForeignKey(blank=True, help_text='Règle appliquée lors de la modération', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applied_content', to='community.moderationrule', verbose_name='Règle de modération'),
        ),
        migrations.AlterField(
            model_name='content',
            name='status',
            field=models.CharField(choices=[('draft', 'Brouillon'), ('pending', "En attente d'approbation"), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='draft', help_text='Statut de modération du contenu', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='content',
            name='subject',
            field=models.ForeignKey(help_text='Matière associée', on_delete=django.db.models.deletion.CASCADE, related_name='community_content', to='skills.subject', verbose_name='Matière'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(help_text='Titre du contenu', max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='content',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='moderationrule',
            name='allowed_subjects',
            field=models.ManyToManyField(blank=True, help_text='Restreindre à des matières spécifiques', to='skills.subject', verbose_name='Matières autorisées'),
        ),
        migrations.AlterField(
            model_name='moderationrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='moderationrule',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Utilisateur qui a créé la règle', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='moderationrule',
            name='description',
            field=models.TextField(help_text='Description de la règle', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='moderationrule',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Cocher pour activer la règle', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='moderationrule',
            name='name',
            field=models.CharField(help_text='Nom unique de la règle', max_length=255, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='moderationrule',
            name='required_word_count',
            field=models.IntegerField(blank=True, help_text='Nombre minimum de mots requis', null=True, verbose_name='Nombre de mots minimum'),
        ),
    ]
