# Generated by Django 4.2.6 on 2026-05-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_alter_content_options_alter_moderationrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='content_file',
            field=models.FileField(blank=True, help_text='Fichier PDF ou autre (si format = PDF ou fichier)', null=True, upload_to='community/', verbose_name='Fichier de contenu'),
        ),
        migrations.AddField(
            model_name='content',
            name='content_format',
            field=models.CharField(choices=[('text', 'Texte brut'), ('pdf', 'Fichier PDF'), ('file', 'Autre fichier')], default='text', help_text='Format du contenu (texte, PDF ou fichier)', max_length=20, verbose_name='Format de contenu'),
        ),
        migrations.AddField(
            model_name='content',
            name='xp_price',
            field=models.IntegerField(default=0, help_text='XP requis pour accéder/télécharger ce contenu (0 = gratuit)', verbose_name='Prix en XP'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=models.TextField(blank=True, help_text='Contenu en texte ou HTML (si format = texte)', verbose_name='Contenu texte'),
        ),
    ]
