# Generated by Django 4.2.6 on 2026-06-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_content_content_file_content_content_format_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='xp_price',
        ),
        migrations.AddField(
            model_name='content',
            name='dc_price',
            field=models.IntegerField(default=0, help_text='DC requis pour accéder/télécharger ce contenu (0 = gratuit)', verbose_name='Prix en DC'),
        ),
    ]
