# Generated by Django 4.2.6 on 2026-06-18 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('community', '0004_remove_content_xp_price_content_dc_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_paid', models.IntegerField(help_text='Prix en DC payé pour le contenu', verbose_name='Prix payé')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, help_text='Date à laquelle le contenu a été acheté', verbose_name="Date d'achat")),
                ('content', models.ForeignKey(help_text='Contenu acheté', on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='community.content', verbose_name='Contenu')),
                ('user', models.ForeignKey(help_text='Utilisateur qui a acheté le contenu', on_delete=django.db.models.deletion.CASCADE, related_name='community_content_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Achat de contenu',
                'verbose_name_plural': 'Achats de contenu',
                'ordering': ['-purchased_at'],
                'unique_together': {('user', 'content')},
            },
        ),
    ]
