# Generated by Django 4.2.6 on 2026-05-14 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-created_at'], 'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, help_text="Photo de profil de l'utilisateur", null=True, upload_to='avatars/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text="Courte biographie de l'utilisateur", verbose_name='Biographie'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date à laquelle le compte a été créé', verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text="Adresse email unique de l'utilisateur", max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text="Prénom de l'utilisateur", max_length=150, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(help_text="Nom de famille de l'utilisateur", max_length=150, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1, help_text="Niveau actuel de l'utilisateur (calculé automatiquement)", verbose_name='Niveau'),
        ),
        migrations.AlterField(
            model_name='user',
            name='total_xp',
            field=models.IntegerField(default=0, help_text="Points d'expérience cumulés (calculé automatiquement)", verbose_name='XP Total'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Dernière modification du profil', verbose_name='Date de mise à jour'),
        ),
    ]
