# Generated by Django 4.2.6 on 2026-05-14 23:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_avatar_alter_user_bio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, help_text='Cocher pour activer le contributeur', verbose_name='Actif')),
                ('can_create_courses', models.BooleanField(default=True, help_text='Autoriser la création de cours', verbose_name='Peut créer des cours')),
                ('can_create_exams', models.BooleanField(default=True, help_text="Autoriser la création d'examens", verbose_name='Peut créer des examens')),
                ('can_create_community_content', models.BooleanField(default=True, help_text='Autoriser la création de contenu communautaire', verbose_name='Peut créer du contenu communautaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contributors', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contributor', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Contributeur',
                'verbose_name_plural': 'Contributeurs',
            },
        ),
    ]
