# Generated by Django 4.2.6 on 2026-06-17 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contributor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du pays', max_length=100, unique=True, verbose_name='Nom du pays')),
                ('code', models.CharField(help_text='Code ISO du pays (ex: FRA, USA)', max_length=3, unique=True, verbose_name='Code ISO')),
                ('is_active', models.BooleanField(default=True, help_text="Cocher pour rendre le pays disponible à l'inscription", verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
            ],
            options={
                'verbose_name': 'Pays',
                'verbose_name_plural': 'Pays',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, help_text="Numéro de téléphone de l'utilisateur", max_length=20, null=True, verbose_name='Numéro de téléphone'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, help_text="Pays de l'utilisateur", null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.country', verbose_name='Pays'),
        ),
    ]
