# Generated by Django 4.2.6 on 2026-06-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_country_user_phone_number_user_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_streak',
            field=models.IntegerField(default=0, help_text="Nombre de jours consécutifs d'activité", verbose_name='Série actuelle'),
        ),
        migrations.AddField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, help_text='Adresse IP de la dernière connexion', null=True, verbose_name='Dernière IP'),
        ),
        migrations.AddField(
            model_name='user',
            name='login_count',
            field=models.IntegerField(default=0, help_text='Nombre total de connexions', verbose_name='Nombre de connexions'),
        ),
        migrations.AddField(
            model_name='user',
            name='longest_streak',
            field=models.IntegerField(default=0, help_text='Plus longue série de jours consécutifs', verbose_name='Plus longue série'),
        ),
        migrations.AddField(
            model_name='user',
            name='total_study_time_minutes',
            field=models.IntegerField(default=0, help_text='Temps total passé sur la plateforme', verbose_name="Temps d'étude total (minutes)"),
        ),
    ]
