# Generated by Django 4.2.6 on 2026-06-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_current_streak_user_last_login_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dc_balance',
            field=models.IntegerField(default=0, help_text='Solde en Decelcone (DC) - monnaie pour les achats sur le site', verbose_name='Solde DC'),
        ),
    ]
