# Generated by Django 4.2.6 on 2026-06-17 23:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_dc_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DCTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Achat'), ('sale', 'Vente'), ('exam_reward', 'Récompense examen'), ('daily_bonus', 'Bonus quotidien'), ('referral', 'Parrainage'), ('admin_grant', 'Octroi admin'), ('admin_deduct', 'Déduction admin')], max_length=20, verbose_name='Type de transaction')),
                ('amount', models.IntegerField(help_text='Montant DC (positif pour gain, négatif pour dépense)', verbose_name='Montant')),
                ('balance_after', models.IntegerField(help_text='Solde DC après cette transaction', verbose_name='Solde après transaction')),
                ('description', models.TextField(blank=True, help_text='Description de la transaction', verbose_name='Description')),
                ('related_content_type', models.CharField(blank=True, help_text='Type de contenu si applicable (course, td, etc.)', max_length=50, verbose_name='Type de contenu lié')),
                ('related_content_id', models.IntegerField(blank=True, null=True, verbose_name='ID du contenu lié')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dc_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Transaction DC',
                'verbose_name_plural': 'Transactions DC',
                'ordering': ['-created_at'],
            },
        ),
    ]
