# Generated by Django 4.2.6 on 2026-06-19 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_contributor_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dctransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Achat'), ('sale', 'Vente'), ('exam_reward', 'Récompense examen'), ('daily_bonus', 'Bonus quotidien'), ('streak_shield', 'Streak Shield'), ('referral', 'Parrainage'), ('admin_grant', 'Octroi admin'), ('admin_deduct', 'Déduction admin')], max_length=20, verbose_name='Type de transaction'),
        ),
    ]
