# Generated by Django 4.2.6 on 2026-06-20 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_dctransaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='Code')),
                ('code_type', models.CharField(choices=[('dc_bonus', 'Bonus DC'), ('xp_boost', 'Boost XP'), ('discount', 'Réduction'), ('special', 'Spécial')], max_length=20, verbose_name='Type de code')),
                ('value', models.IntegerField(help_text='Valeur du code (DC, %, etc.)', verbose_name='Valeur')),
                ('max_uses', models.IntegerField(blank=True, help_text='Null pour illimité', null=True, verbose_name='Utilisations max')),
                ('used_count', models.IntegerField(default=0, verbose_name='Utilisations')),
                ('valid_from', models.DateTimeField(verbose_name='Valide à partir de')),
                ('valid_until', models.DateTimeField(verbose_name="Valide jusqu'à")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promo_codes_created', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Code Promo',
                'verbose_name_plural': 'Codes Promo',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_code', models.CharField(max_length=20, unique=True, verbose_name='Code de parrainage')),
                ('reward_dc', models.IntegerField(default=50, help_text="DC donnés au parrain quand le filleul s'inscrit", verbose_name='Récompense DC')),
                ('referred_reward_dc', models.IntegerField(default=25, help_text="DC donnés au filleul quand il s'inscrit", verbose_name='Récompense filleul')),
                ('is_completed', models.BooleanField(default=False, help_text='True quand le filleul a complété les conditions', verbose_name='Complété')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de complétion')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('referred', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='referral_received', to=settings.AUTH_USER_MODEL, verbose_name='Filleul')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals_made', to=settings.AUTH_USER_MODEL, verbose_name='Parrain')),
            ],
            options={
                'verbose_name': 'Parrainage',
                'verbose_name_plural': 'Parrainages',
                'unique_together': {('referrer', 'referred')},
            },
        ),
        migrations.CreateModel(
            name='PromoCodeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'utilisation")),
                ('reward_given', models.IntegerField(help_text='DC ou XP donnés', verbose_name='Récompense donnée')),
                ('promo_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='accounts.promocode', verbose_name='Code promo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_usages', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Utilisation de code promo',
                'verbose_name_plural': 'Utilisations de codes promo',
                'unique_together': {('promo_code', 'user')},
            },
        ),
    ]
