# Generated by Django 4.2.6 on 2026-06-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_referral_referred'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dctransaction',
            name='transaction_type',
            field=models.CharField(
                choices=[
                    ('purchase', 'Achat pack DC'),
                    ('manual_payment', 'Paiement manuel validé'),
                    ('recharge_code', 'Code de recharge'),
                    ('sale', 'Vente'),
                    ('exam_reward', 'Récompense examen'),
                    ('daily_bonus', 'Bonus quotidien'),
                    ('streak_shield', 'Streak Shield'),
                    ('referral', 'Parrainage'),
                    ('admin_grant', 'Octroi admin'),
                    ('admin_deduct', 'Déduction admin'),
                ],
                max_length=20,
                verbose_name='Type de transaction',
            ),
        ),
    ]
