# Generated by Django 4.2 on 2026-06-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_dctransaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='theme_preference',
            field=models.CharField(choices=[('light', 'Clair'), ('dark', 'Sombre'), ('auto', 'Automatique')], default='auto', help_text="Préférence de thème de l'utilisateur", max_length=10, verbose_name='Préférence de thème'),
        ),
    ]
