# Generated by Django 4.2 on 2026-06-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_user_theme_preference'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('9th', '9ème année'), ('10th', '10ème année'), ('11th', '11ème année'), ('12th', '12ème année / Terminale'), ('bac', 'Baccalauréat'), ('license1', 'Licence 1'), ('license2', 'Licence 2'), ('license3', 'Licence 3'), ('master1', 'Master 1'), ('master2', 'Master 2'), ('doctorate', 'Doctorat'), ('other', 'Autre')], help_text="Niveau scolaire de l'utilisateur", max_length=20, verbose_name='Niveau scolaire'),
        ),
    ]
