# Generated by Django 4.2 on 2026-06-30 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_grade_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Contributeur ou admin qui a créé ce pays', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_countries', to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.CreateModel(
            name='VisitorTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(help_text='Adresse IP du visiteur', verbose_name='Adresse IP')),
                ('user_agent', models.TextField(blank=True, help_text='Navigateur du visiteur', verbose_name='User Agent')),
                ('path', models.CharField(help_text='URL visitée', max_length=255, verbose_name='Chemin')),
                ('session_key', models.CharField(blank=True, help_text='Clé de session', max_length=255, verbose_name='Session')),
                ('visit_date', models.DateField(help_text='Date de la visite', verbose_name='Date de visite')),
                ('visit_time', models.TimeField(help_text='Heure de la visite', verbose_name='Heure de visite')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('user', models.ForeignKey(blank=True, help_text='Utilisateur connecté (si applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Visiteur',
                'verbose_name_plural': 'Visiteurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GradeLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du niveau scolaire (ex: 6ème, 5ème, etc.)', max_length=100, unique=True, verbose_name='Nom du niveau')),
                ('description', models.TextField(blank=True, help_text='Description du niveau scolaire', verbose_name='Description')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage (plus petit = plus haut)", verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, help_text='Cocher pour rendre le niveau disponible', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(blank=True, help_text='Contributeur ou admin qui a créé ce niveau', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grade_levels', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Niveau scolaire',
                'verbose_name_plural': 'Niveaux scolaires',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='visitortracking',
            index=models.Index(fields=['visit_date'], name='accounts_vi_visit_d_9cb1aa_idx'),
        ),
        migrations.AddIndex(
            model_name='visitortracking',
            index=models.Index(fields=['visit_time'], name='accounts_vi_visit_t_ef0fff_idx'),
        ),
        migrations.AddIndex(
            model_name='visitortracking',
            index=models.Index(fields=['ip_address'], name='accounts_vi_ip_addr_2c382b_idx'),
        ),
    ]
