# Generated by Django 4.2 on 2026-07-02 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_country_created_by_visitortracking_gradelevel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country_code',
            field=models.CharField(blank=True, help_text='Code pays ISO à 2 lettres', max_length=2, null=True, verbose_name='Code Pays'),
        ),
    ]
