# Generated by Django 4.2 on 2026-07-05 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_user_country_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitortracking',
            name='session_key',
            field=models.CharField(blank=True, help_text='Clé de session', max_length=255, null=True, verbose_name='Session'),
        ),
    ]
