# Generated by Django 4.2.6 on 2026-05-14 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0002_alter_subject_options_alter_userskill_options_and_more'),
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order'], 'verbose_name': 'Choix de réponse', 'verbose_name_plural': 'Choix de réponses'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at'], 'verbose_name': 'Examen', 'verbose_name_plural': 'Examens'},
        ),
        migrations.AlterModelOptions(
            name='examsession',
            options={'ordering': ['-started_at'], 'verbose_name': "Session d'examen", 'verbose_name_plural': "Sessions d'examen"},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Réponse utilisateur', 'verbose_name_plural': 'Réponses utilisateurs'},
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='⚠️ Cocher SEULEMENT pour les bonnes réponses', verbose_name='Correct'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='order',
            field=models.IntegerField(default=0, help_text="Ordre d'affichage du choix", verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(help_text='Question à laquelle ce choix appartient', on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='exams.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(help_text='Texte de la réponse', max_length=500, verbose_name='Texte'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text="Utilisateur qui a créé l'examen", null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, help_text="Description détaillée de l'examen", verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='difficulty',
            field=models.IntegerField(default=1, help_text='Niveau de difficulté (1=Facile, 5=Difficile)', verbose_name='Difficulté'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, help_text="Cocher pour rendre l'examen disponible aux utilisateurs", verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_score',
            field=models.IntegerField(default=60, help_text="Pourcentage minimum pour réussir l'examen", verbose_name='Score de passage'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(help_text="Matière associée à l'examen", on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='skills.subject', verbose_name='Matière'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='time_limit',
            field=models.IntegerField(blank=True, help_text='Limite de temps en minutes (laisser vide pour illimité)', null=True, verbose_name='Limite de temps'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(help_text="Titre de l'examen", max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Heure de fin'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='exam',
            field=models.ForeignKey(help_text='Examen passé', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='exams.exam', verbose_name='Examen'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Indique si la session est terminée', verbose_name='Terminé'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='passed',
            field=models.BooleanField(blank=True, help_text="Indique si l'examen a été réussi", null=True, verbose_name='Réussi'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='score',
            field=models.IntegerField(blank=True, help_text='Score en pourcentage', null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Heure de début'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='user',
            field=models.ForeignKey(help_text="Utilisateur qui a passé l'examen", on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(help_text='Examen auquel cette question appartient', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='Examen'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=0, help_text="Ordre d'affichage de la question", verbose_name='Ordre'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Énoncé de la question', verbose_name='Énoncé'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Indique si la réponse est correcte (évaluation stricte)', verbose_name='Correct'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(help_text='Question répondue', on_delete=django.db.models.deletion.CASCADE, to='exams.question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_choices',
            field=models.ManyToManyField(help_text="Choix de réponse sélectionnés par l'utilisateur", related_name='user_answers', to='exams.choice', verbose_name='Choix sélectionnés'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='session',
            field=models.ForeignKey(help_text="Session d'examen associée", on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.examsession', verbose_name='Session'),
        ),
    ]
