# Generated by Django 4.2.6 on 2026-05-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_choice_options_alter_exam_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('manual', 'Questions saisies manuellement'), ('file', 'Questions sur fichier (PDF/Image)')], default='manual', help_text="Type d'examen : questions manuelles ou sur fichier", max_length=20, verbose_name="Type d'examen"),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_file',
            field=models.FileField(blank=True, help_text='Fichier PDF ou image contenant les questions (si type = fichier)', null=True, upload_to='exams/questions/', verbose_name='Fichier de questions'),
        ),
        migrations.AddField(
            model_name='question',
            name='answer_options',
            field=models.JSONField(blank=True, default=dict, help_text='Options de réponse prédéfinies (ex: {"A": "Option A", "B": "Option B", ...})', verbose_name='Options de réponse'),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answers',
            field=models.JSONField(blank=True, default=list, help_text='Liste des lettres des réponses correctes (ex: ["A", "C"])', verbose_name='Réponses correctes'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_letters',
            field=models.JSONField(blank=True, default=list, help_text='Lettres des réponses sélectionnées (ex: ["A", "C"])', verbose_name='Lettres sélectionnées'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, help_text='Énoncé de la question (vide si questions sur fichier)', verbose_name='Énoncé'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, help_text="Choix de réponse sélectionnés par l'utilisateur", related_name='user_answers', to='exams.choice', verbose_name='Choix sélectionnés'),
        ),
    ]
