# Generated by Django 4.2.6 on 2026-05-14 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_exam_exam_type_exam_question_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_options',
        ),
        migrations.RemoveField(
            model_name='question',
            name='correct_answers',
        ),
        migrations.RemoveField(
            model_name='useranswer',
            name='selected_letters',
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, help_text="Choix de réponse sélectionnés par l'utilisateur (pour examens manuels)", related_name='user_answers', to='exams.choice', verbose_name='Choix sélectionnés'),
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], help_text="Label de l'option (A, B, C, D, 1, 2, 3, etc.)", max_length=10, verbose_name='Label')),
                ('text', models.CharField(help_text="Texte de l'option de réponse", max_length=500, verbose_name="Texte de l'option")),
                ('is_correct', models.BooleanField(default=False, help_text='Cocher si cette option est une bonne réponse', verbose_name='Réponse correcte')),
                ('order', models.IntegerField(default=0, help_text="Ordre d'affichage de l'option", verbose_name='Ordre')),
                ('question', models.ForeignKey(help_text='Question à laquelle cette option appartient', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question', verbose_name='Question')),
            ],
            options={
                'verbose_name': 'Option de réponse',
                'verbose_name_plural': 'Options de réponse',
                'ordering': ['order'],
                'unique_together': {('question', 'label')},
            },
        ),
        migrations.AddField(
            model_name='useranswer',
            name='selected_options',
            field=models.ManyToManyField(blank=True, help_text="Options de réponse sélectionnées par l'utilisateur (pour examens sur fichier)", related_name='user_answers', to='exams.questionoption', verbose_name='Options sélectionnées'),
        ),
    ]
