# Generated by Django 4.2.6 on 2026-05-15 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_remove_question_answer_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionoption',
            unique_together=set(),
        ),
    ]
