# Generated by Django 4.2.6 on 2026-05-15 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_unify_choice_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, help_text="Choix de réponse sélectionnés par l'utilisateur", related_name='user_answers', to='exams.choice', verbose_name='Choix sélectionnés'),
        ),
    ]
