# Generated by Django 4.2.6 on 2026-05-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_alter_useranswer_selected_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='xp_penalty_per_wrong',
            field=models.IntegerField(default=5, help_text='XP perdu pour chaque mauvaise réponse (0 = pas de pénalité)', verbose_name='Pénalité XP par mauvaise réponse'),
        ),
        migrations.AddField(
            model_name='exam',
            name='xp_per_correct',
            field=models.IntegerField(default=10, help_text='XP gagné pour chaque bonne réponse', verbose_name='XP par bonne réponse'),
        ),
    ]
