# Generated by Django 4.2.6 on 2026-05-17 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exam_xp_penalty_per_wrong_exam_xp_per_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='is_time_expired',
            field=models.BooleanField(default=False, help_text="Indique si le temps de l'examen a expiré", verbose_name='Temps expiré'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='time_remaining_seconds',
            field=models.IntegerField(blank=True, help_text='Temps restant en secondes (pour les examens chronométrés)', null=True, verbose_name='Temps restant (secondes)'),
        ),
    ]
