# Generated by Django 4.2.6 on 2026-06-17 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_examsession_is_time_expired_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examsession',
            unique_together=set(),
        ),
    ]
