# Generated by Django 4.2.6 on 2026-06-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_alter_examsession_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='is_best_attempt',
            field=models.BooleanField(default=False, help_text="Indique si c'est la meilleure tentative de l'utilisateur pour cet examen", verbose_name='Meilleure tentative'),
        ),
    ]
