# Generated by Django 4.2.6 on 2026-06-17 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_examsession_is_best_attempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='xp_earned',
            field=models.IntegerField(default=0, help_text='XP gagné pour cette tentative', verbose_name='XP gagné'),
        ),
    ]
