# Generated by Django 4.2.6 on 2026-06-17 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_examsession_xp_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='randomize_choices',
            field=models.BooleanField(default=False, help_text="Cocher pour mélanger l'ordre des choix de réponse à chaque tentative", verbose_name='Randomiser les choix'),
        ),
        migrations.AddField(
            model_name='exam',
            name='randomize_questions',
            field=models.BooleanField(default=False, help_text="Cocher pour mélanger l'ordre des questions à chaque tentative", verbose_name='Randomiser les questions'),
        ),
        migrations.AddField(
            model_name='exam',
            name='xp_reward_for_contributor',
            field=models.IntegerField(default=0, help_text="XP donnés au contributeur créateur quand un utilisateur rate l'examen", verbose_name='XP récompense pour contributeur'),
        ),
    ]
