# Generated by Django 4.2.6 on 2026-06-17 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0013_exam_randomize_choices_exam_randomize_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='dc_earned',
            field=models.IntegerField(default=0, help_text='DC gagné pour cette tentative', verbose_name='DC gagné'),
        ),
    ]
