# Generated by Django 4.2 on 2026-06-30 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du plan')),
                ('plan_type', models.CharField(choices=[('free', 'Gratuit'), ('premium', 'Premium'), ('pro', 'Professionnel')], max_length=20, verbose_name='Type de plan')),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='monthly', max_length=20, verbose_name='Cycle de facturation')),
                ('dc_price', models.IntegerField(help_text='Prix en DC pour ce plan', verbose_name='Prix en DC')),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, verbose_name='ID prix Stripe')),
                ('features', models.JSONField(default=dict, help_text='Liste des fonctionnalités incluses', verbose_name='Fonctionnalités')),
                ('max_courses_per_month', models.IntegerField(blank=True, null=True, verbose_name='Max cours/mois')),
                ('max_exams_per_month', models.IntegerField(blank=True, null=True, verbose_name='Max examens/mois')),
                ('max_tds_per_month', models.IntegerField(blank=True, null=True, verbose_name='Max TDs/mois')),
                ('has_certificates', models.BooleanField(default=False, verbose_name='Certificats')),
                ('has_mentoring', models.BooleanField(default=False, verbose_name='Mentoring')),
                ('has_analytics', models.BooleanField(default=False, verbose_name='Analytics avancés')),
                ('has_priority_support', models.BooleanField(default=False, verbose_name='Support prioritaire')),
                ('has_ad_free', models.BooleanField(default=False, verbose_name='Sans publicité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Populaire')),
                ('order', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
            ],
            options={
                'verbose_name': "Plan d'abonnement",
                'verbose_name_plural': "Plans d'abonnement",
                'ordering': ['order', 'dc_price'],
            },
        ),
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('cancelled', 'Annulé'), ('expired', 'Expiré'), ('pending', 'En attente')], default='pending', max_length=20, verbose_name='Statut')),
                ('start_date', models.DateTimeField(verbose_name='Date de début')),
                ('end_date', models.DateTimeField(verbose_name='Date de fin')),
                ('auto_renew', models.BooleanField(default=True, verbose_name='Renouvellement automatique')),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, verbose_name='ID abonnement Stripe')),
                ('last_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Date du dernier paiement')),
                ('next_payment_date', models.DateTimeField(blank=True, null=True, verbose_name='Date du prochain paiement')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('cancellation_reason', models.TextField(blank=True, verbose_name="Raison de l'annulation")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subscriptions.subscriptionplan', verbose_name='Plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Abonnement utilisateur',
                'verbose_name_plural': 'Abonnements utilisateurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('subscription_start', "Début d'abonnement"), ('subscription_renewal', "Renouvellement d'abonnement"), ('subscription_upgrade', "Upgrade d'abonnement"), ('subscription_downgrade', "Downgrade d'abonnement"), ('subscription_cancel', "Annulation d'abonnement")], max_length=30, verbose_name='Type de transaction')),
                ('dc_amount', models.IntegerField(verbose_name='Montant DC')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, verbose_name='ID Payment Intent Stripe')),
                ('plan_name', models.CharField(max_length=100, verbose_name='Nom du plan')),
                ('plan_type', models.CharField(max_length=20, verbose_name='Type de plan')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='subscriptions.usersubscription', verbose_name='Abonnement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Transaction d'abonnement",
                'verbose_name_plural': "Transactions d'abonnement",
                'ordering': ['-created_at'],
            },
        ),
    ]
