# Generated by Django 4.2.6 on 2026-05-14 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0002_alter_subject_options_alter_userskill_options_and_more'),
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correctedtd',
            options={'ordering': ['-created_at'], 'verbose_name': 'TD corrigé', 'verbose_name_plural': 'TD corrigés'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cours', 'verbose_name_plural': 'Cours'},
        ),
        migrations.AlterModelOptions(
            name='courseprogress',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Progression de cours', 'verbose_name_plural': 'Progressions de cours'},
        ),
        migrations.AlterModelOptions(
            name='td',
            options={'ordering': ['-created_at'], 'verbose_name': 'TD', 'verbose_name_plural': 'TD'},
        ),
        migrations.AlterModelOptions(
            name='tdprogress',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Progression de TD', 'verbose_name_plural': 'Progressions de TD'},
        ),
        migrations.AlterField(
            model_name='correctedtd',
            name='correction',
            field=models.TextField(help_text='Corrections détaillées et solutions des exercices', verbose_name='Correction'),
        ),
        migrations.AlterField(
            model_name='correctedtd',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='correctedtd',
            name='td',
            field=models.OneToOneField(help_text='TD associé à cette correction', on_delete=django.db.models.deletion.CASCADE, related_name='correction', to='learning.td', verbose_name='TD'),
        ),
        migrations.AlterField(
            model_name='correctedtd',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='course',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Auteur du cours', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(help_text='Contenu du cours en texte ou HTML', verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='course',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, help_text='Description courte du cours', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Cocher pour rendre le cours visible aux utilisateurs', verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(help_text='Matière associée au cours', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='skills.subject', verbose_name='Matière'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(help_text='Titre du cours', max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle le cours a été terminé', null=True, verbose_name='Date de complétion'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='course',
            field=models.ForeignKey(help_text='Cours concerné', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.course', verbose_name='Cours'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Indique si le cours a été terminé', verbose_name='Terminé'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='courseprogress',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='course_progress', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='td',
            name='author',
            field=models.ForeignKey(blank=True, help_text='Auteur du TD', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Auteur'),
        ),
        migrations.AlterField(
            model_name='td',
            name='content',
            field=models.TextField(help_text='Énoncé des exercices en texte ou HTML', verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='td',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='td',
            name='description',
            field=models.TextField(blank=True, help_text='Description courte du TD', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='td',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Cocher pour rendre le TD visible aux utilisateurs', verbose_name='Publié'),
        ),
        migrations.AlterField(
            model_name='td',
            name='subject',
            field=models.ForeignKey(help_text='Matière associée au TD', on_delete=django.db.models.deletion.CASCADE, related_name='tds', to='skills.subject', verbose_name='Matière'),
        ),
        migrations.AlterField(
            model_name='td',
            name='title',
            field=models.CharField(help_text='Titre du TD', max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='td',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='tdprogress',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Date à laquelle le TD a été terminé', null=True, verbose_name='Date de complétion'),
        ),
        migrations.AlterField(
            model_name='tdprogress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='tdprogress',
            name='is_completed',
            field=models.BooleanField(default=False, help_text='Indique si le TD a été terminé', verbose_name='Terminé'),
        ),
        migrations.AlterField(
            model_name='tdprogress',
            name='score',
            field=models.IntegerField(blank=True, help_text='Score auto-déclaré (0-100)', null=True, verbose_name='Score'),
        ),
        migrations.AlterField(
            model_name='tdprogress',
            name='td',
            field=models.ForeignKey(help_text='TD concerné', on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.td', verbose_name='TD'),
        ),
        migrations.AlterField(
            model_name='tdprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='tdprogress',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='td_progress', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
