# Generated by Django 4.2.6 on 2026-05-14 21:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0002_alter_correctedtd_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctedtd',
            name='content_type',
            field=models.CharField(choices=[('text', 'Texte brut'), ('pdf', 'Fichier PDF'), ('file', 'Autre fichier')], default='text', help_text='Type de contenu de la correction', max_length=20, verbose_name='Type de contenu'),
        ),
        migrations.AddField(
            model_name='correctedtd',
            name='correction_file',
            field=models.FileField(blank=True, help_text='Fichier PDF ou autre de la correction (si type = PDF ou fichier)', null=True, upload_to='corrections/', verbose_name='Fichier de correction'),
        ),
        migrations.AddField(
            model_name='correctedtd',
            name='xp_price',
            field=models.IntegerField(default=0, help_text='XP requis pour accéder/télécharger cette correction (0 = gratuit)', verbose_name='Prix en XP'),
        ),
        migrations.AddField(
            model_name='course',
            name='content_file',
            field=models.FileField(blank=True, help_text='Fichier PDF ou autre (si type = PDF ou fichier)', null=True, upload_to='courses/', verbose_name='Fichier de contenu'),
        ),
        migrations.AddField(
            model_name='course',
            name='content_type',
            field=models.CharField(choices=[('text', 'Texte brut'), ('pdf', 'Fichier PDF'), ('file', 'Autre fichier')], default='text', help_text='Type de contenu du cours', max_length=20, verbose_name='Type de contenu'),
        ),
        migrations.AddField(
            model_name='course',
            name='xp_price',
            field=models.IntegerField(default=0, help_text='XP requis pour accéder/télécharger ce cours (0 = gratuit)', verbose_name='Prix en XP'),
        ),
        migrations.AddField(
            model_name='td',
            name='content_file',
            field=models.FileField(blank=True, help_text='Fichier PDF ou autre (si type = PDF ou fichier)', null=True, upload_to='tds/', verbose_name='Fichier de contenu'),
        ),
        migrations.AddField(
            model_name='td',
            name='content_type',
            field=models.CharField(choices=[('text', 'Texte brut'), ('pdf', 'Fichier PDF'), ('file', 'Autre fichier')], default='text', help_text='Type de contenu du TD', max_length=20, verbose_name='Type de contenu'),
        ),
        migrations.AddField(
            model_name='td',
            name='xp_price',
            field=models.IntegerField(default=0, help_text='XP requis pour accéder/télécharger ce TD (0 = gratuit)', verbose_name='Prix en XP'),
        ),
        migrations.AlterField(
            model_name='correctedtd',
            name='correction',
            field=models.TextField(blank=True, help_text='Corrections détaillées et solutions des exercices (si type = texte)', verbose_name='Correction texte'),
        ),
        migrations.AlterField(
            model_name='course',
            name='content',
            field=models.TextField(blank=True, help_text='Contenu du cours en texte ou HTML (si type = texte)', verbose_name='Contenu texte'),
        ),
        migrations.AlterField(
            model_name='td',
            name='content',
            field=models.TextField(blank=True, help_text='Énoncé des exercices en texte ou HTML (si type = texte)', verbose_name='Contenu texte'),
        ),
        migrations.CreateModel(
            name='ContentPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('course', 'Cours'), ('td', 'TD'), ('corrected_td', 'TD corrigé')], help_text='Type de contenu acheté', max_length=20, verbose_name='Type de contenu')),
                ('course_id', models.IntegerField(blank=True, help_text='ID du cours acheté', null=True, verbose_name='ID cours')),
                ('td_id', models.IntegerField(blank=True, help_text='ID du TD acheté', null=True, verbose_name='ID TD')),
                ('corrected_td_id', models.IntegerField(blank=True, help_text='ID du TD corrigé acheté', null=True, verbose_name='ID TD corrigé')),
                ('xp_paid', models.IntegerField(help_text="Quantité d'XP payée", verbose_name='XP payé')),
                ('purchased_at', models.DateTimeField(auto_now_add=True, help_text='Date à laquelle le contenu a été acheté', verbose_name="Date d'achat")),
                ('user', models.ForeignKey(help_text='Utilisateur qui a acheté le contenu', on_delete=django.db.models.deletion.CASCADE, related_name='content_purchases', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Achat de contenu',
                'verbose_name_plural': 'Achats de contenu',
                'ordering': ['-purchased_at'],
            },
        ),
    ]
