# Generated by Django 4.2.6 on 2026-06-17 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0003_correctedtd_content_type_correctedtd_correction_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctedtd',
            name='current_version',
            field=models.IntegerField(default=1, help_text='Numéro de version actuel de la correction', verbose_name='Version actuelle'),
        ),
        migrations.AddField(
            model_name='course',
            name='current_version',
            field=models.IntegerField(default=1, help_text='Numéro de version actuel du cours', verbose_name='Version actuelle'),
        ),
        migrations.AddField(
            model_name='td',
            name='current_version',
            field=models.IntegerField(default=1, help_text='Numéro de version actuel du TD', verbose_name='Version actuelle'),
        ),
        migrations.CreateModel(
            name='ContentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('course', 'Cours'), ('td', 'TD'), ('corrected_td', 'TD corrigé')], max_length=20, verbose_name='Type de contenu')),
                ('content_id', models.IntegerField(verbose_name='ID du contenu')),
                ('version_number', models.IntegerField(verbose_name='Numéro de version')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('content', models.TextField(blank=True, verbose_name='Contenu texte')),
                ('content_file', models.FileField(blank=True, null=True, upload_to='versions/', verbose_name='Fichier de contenu')),
                ('change_summary', models.TextField(help_text='Description des changements dans cette version', verbose_name='Résumé des modifications')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Version de contenu',
                'verbose_name_plural': 'Versions de contenu',
                'ordering': ['-version_number'],
                'unique_together': {('content_type', 'content_id', 'version_number')},
            },
        ),
    ]
