# Generated by Django 4.2.6 on 2026-06-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0004_correctedtd_current_version_course_current_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentpurchase',
            name='xp_paid',
        ),
        migrations.RemoveField(
            model_name='correctedtd',
            name='xp_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='xp_price',
        ),
        migrations.RemoveField(
            model_name='td',
            name='xp_price',
        ),
        migrations.AddField(
            model_name='contentpurchase',
            name='dc_paid',
            field=models.IntegerField(default=22, help_text='Quantité de DC payée', verbose_name='DC payé'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correctedtd',
            name='dc_price',
            field=models.IntegerField(default=0, help_text='DC requis pour accéder/télécharger cette correction (0 = gratuit)', verbose_name='Prix en DC'),
        ),
        migrations.AddField(
            model_name='course',
            name='dc_price',
            field=models.IntegerField(default=0, help_text='DC requis pour accéder/télécharger ce cours (0 = gratuit)', verbose_name='Prix en DC'),
        ),
        migrations.AddField(
            model_name='td',
            name='dc_price',
            field=models.IntegerField(default=0, help_text='DC requis pour accéder/télécharger ce TD (0 = gratuit)', verbose_name='Prix en DC'),
        ),
    ]
