# Generated by Django 4.2 on 2026-06-29 19:46

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('learning', '0005_remove_contentpurchase_xp_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correctedtd',
            name='content_type',
            field=models.CharField(choices=[('text', 'Texte brut'), ('pdf', 'Fichier PDF'), ('image', 'Image'), ('file', 'Autre fichier')], default='text', help_text='Type de contenu de la correction', max_length=20, verbose_name='Type de contenu'),
        ),
        migrations.AlterField(
            model_name='course',
            name='content_type',
            field=models.CharField(choices=[('text', 'Texte brut'), ('pdf', 'Fichier PDF'), ('image', 'Image'), ('file', 'Autre fichier')], default='text', help_text='Type de contenu du cours', max_length=20, verbose_name='Type de contenu'),
        ),
        migrations.AlterField(
            model_name='td',
            name='content_type',
            field=models.CharField(choices=[('text', 'Texte brut'), ('pdf', 'Fichier PDF'), ('image', 'Image'), ('file', 'Autre fichier')], default='text', help_text='Type de contenu du TD', max_length=20, verbose_name='Type de contenu'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('course', 'Cours'), ('td', 'TD'), ('corrected_td', 'TD corrigé')], max_length=20, verbose_name='Type de contenu')),
                ('rating', models.IntegerField(help_text='Note de 1 à 5 étoiles', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Note')),
                ('comment', models.TextField(blank=True, help_text='Commentaire détaillé', verbose_name='Commentaire')),
                ('is_approved', models.BooleanField(default=True, help_text='Indique si la review est visible', verbose_name='Approuvé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('corrected_td', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning.correctedtd', verbose_name='TD corrigé')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning.course', verbose_name='Cours')),
                ('td', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning.td', verbose_name='TD')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Avis',
                'verbose_name_plural': 'Avis',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'content_type', 'course', 'td', 'corrected_td')},
            },
        ),
    ]
