# Generated by Django 4.2 on 2026-06-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_alter_correctedtd_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='correctedtd',
            name='country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('CI', "Côte d'Ivoire"), ('ML', 'Mali'), ('SN', 'Sénégal'), ('BF', 'Burkina Faso'), ('CM', 'Cameroun'), ('CD', 'République Démocratique du Congo'), ('GA', 'Gabon'), ('MG', 'Madagascar'), ('NE', 'Niger'), ('TG', 'Togo'), ('BJ', 'Bénin'), ('HT', 'Haïti'), ('CA', 'Canada'), ('BE', 'Belgique'), ('CH', 'Suisse'), ('LU', 'Luxembourg'), ('MA', 'Maroc'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('US', 'États-Unis'), ('GB', 'Royaume-Uni'), ('DE', 'Allemagne'), ('OTHER', 'Autre')], help_text='Pays pour lequel cette correction est destinée', max_length=5, verbose_name='Pays cible'),
        ),
        migrations.AddField(
            model_name='correctedtd',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('9th', '9ème année'), ('10th', '10ème année'), ('11th', '11ème année'), ('12th', '12ème année / Terminale'), ('bac', 'Baccalauréat'), ('license1', 'Licence 1'), ('license2', 'Licence 2'), ('license3', 'Licence 3'), ('master1', 'Master 1'), ('master2', 'Master 2'), ('doctorate', 'Doctorat'), ('other', 'Autre')], help_text='Niveau scolaire cible', max_length=20, verbose_name='Niveau scolaire'),
        ),
        migrations.AddField(
            model_name='course',
            name='country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('CI', "Côte d'Ivoire"), ('ML', 'Mali'), ('SN', 'Sénégal'), ('BF', 'Burkina Faso'), ('CM', 'Cameroun'), ('CD', 'République Démocratique du Congo'), ('GA', 'Gabon'), ('MG', 'Madagascar'), ('NE', 'Niger'), ('TG', 'Togo'), ('BJ', 'Bénin'), ('HT', 'Haïti'), ('CA', 'Canada'), ('BE', 'Belgique'), ('CH', 'Suisse'), ('LU', 'Luxembourg'), ('MA', 'Maroc'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('US', 'États-Unis'), ('GB', 'Royaume-Uni'), ('DE', 'Allemagne'), ('OTHER', 'Autre')], help_text='Pays pour lequel ce cours est destiné', max_length=5, verbose_name='Pays cible'),
        ),
        migrations.AddField(
            model_name='course',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('9th', '9ème année'), ('10th', '10ème année'), ('11th', '11ème année'), ('12th', '12ème année / Terminale'), ('bac', 'Baccalauréat'), ('license1', 'Licence 1'), ('license2', 'Licence 2'), ('license3', 'Licence 3'), ('master1', 'Master 1'), ('master2', 'Master 2'), ('doctorate', 'Doctorat'), ('other', 'Autre')], help_text='Niveau scolaire cible', max_length=20, verbose_name='Niveau scolaire'),
        ),
        migrations.AddField(
            model_name='td',
            name='country',
            field=models.CharField(blank=True, choices=[('FR', 'France'), ('CI', "Côte d'Ivoire"), ('ML', 'Mali'), ('SN', 'Sénégal'), ('BF', 'Burkina Faso'), ('CM', 'Cameroun'), ('CD', 'République Démocratique du Congo'), ('GA', 'Gabon'), ('MG', 'Madagascar'), ('NE', 'Niger'), ('TG', 'Togo'), ('BJ', 'Bénin'), ('HT', 'Haïti'), ('CA', 'Canada'), ('BE', 'Belgique'), ('CH', 'Suisse'), ('LU', 'Luxembourg'), ('MA', 'Maroc'), ('TN', 'Tunisie'), ('DZ', 'Algérie'), ('US', 'États-Unis'), ('GB', 'Royaume-Uni'), ('DE', 'Allemagne'), ('OTHER', 'Autre')], help_text='Pays pour lequel ce TD est destiné', max_length=5, verbose_name='Pays cible'),
        ),
        migrations.AddField(
            model_name='td',
            name='grade_level',
            field=models.CharField(blank=True, choices=[('9th', '9ème année'), ('10th', '10ème année'), ('11th', '11ème année'), ('12th', '12ème année / Terminale'), ('bac', 'Baccalauréat'), ('license1', 'Licence 1'), ('license2', 'Licence 2'), ('license3', 'Licence 3'), ('master1', 'Master 1'), ('master2', 'Master 2'), ('doctorate', 'Doctorat'), ('other', 'Autre')], help_text='Niveau scolaire cible', max_length=20, verbose_name='Niveau scolaire'),
        ),
    ]
