# Generated by Django 4.2.6 on 2026-05-14 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Matière', 'verbose_name_plural': 'Matières'},
        ),
        migrations.AlterModelOptions(
            name='userskill',
            options={'ordering': ['-skill_percentage'], 'verbose_name': 'Compétence utilisateur', 'verbose_name_plural': 'Compétences utilisateurs'},
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='description',
            field=models.TextField(blank=True, help_text='Description détaillée de la matière', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='icon',
            field=models.CharField(blank=True, help_text="Nom de l'icône ou emoji", max_length=50, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Nom unique de la matière', max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, help_text='Date de la dernière activité dans cette matière', verbose_name='Dernière activité'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='skill_percentage',
            field=models.IntegerField(default=0, help_text='Niveau de compétence en pourcentage (calculé automatiquement)', verbose_name='Pourcentage de compétence'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='subject',
            field=models.ForeignKey(help_text='Matière concernée', on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to='skills.subject', verbose_name='Matière'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='total_courses_read',
            field=models.IntegerField(default=0, help_text='Nombre total de cours lus dans cette matière', verbose_name='Total de cours lus'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='total_exams_taken',
            field=models.IntegerField(default=0, help_text="Nombre total d'examens passés dans cette matière", verbose_name="Total d'examens passés"),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='total_td_completed',
            field=models.IntegerField(default=0, help_text='Nombre total de TD complétés dans cette matière', verbose_name='Total de TD complétés'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='userskill',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
