# Generated by Django 4.2.6 on 2026-06-20 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_alter_subject_options_alter_userskill_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='icon_image',
            field=models.ImageField(blank=True, help_text="Image personnalisée pour l'icône de la matière", null=True, upload_to='subject_icons/', verbose_name="Image de l'icône"),
        ),
        migrations.AddField(
            model_name='subject',
            name='use_image',
            field=models.BooleanField(default=False, help_text="Cocher pour utiliser l'image au lieu de l'icône", verbose_name="Utiliser l'image"),
        ),
    ]
