# Generated by Django 4.2 on 2026-07-05 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_subject_icon_image_subject_use_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom de la compétence', max_length=100, verbose_name='Nom')),
                ('description', models.TextField(blank=True, help_text='Description détaillée de la compétence', verbose_name='Description')),
                ('subject', models.ForeignKey(help_text='Matière associée', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Compétence',
                'verbose_name_plural': 'Compétences',
                'ordering': ['name'],
            },
        ),
    ]
