# Generated by Django 4.2 on 2026-06-30 23:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0003_subject_icon_image_subject_use_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField(verbose_name='Date prévue')),
                ('scheduled_time', models.TimeField(verbose_name='Heure prévue')),
                ('duration_minutes', models.IntegerField(verbose_name='Durée (minutes)')),
                ('dc_price', models.IntegerField(verbose_name='Prix DC')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Payé')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmé'), ('in_progress', 'En cours'), ('completed', 'Terminé'), ('cancelled', 'Annulé'), ('no_show', 'Absent')], default='pending', max_length=20, verbose_name='Statut')),
                ('meeting_link', models.URLField(blank=True, verbose_name='Lien de réunion')),
                ('meeting_notes', models.TextField(blank=True, verbose_name='Notes de réunion')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'annulation")),
                ('cancellation_reason', models.TextField(blank=True, verbose_name="Raison d'annulation")),
                ('rating', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Note')),
                ('review', models.TextField(blank=True, verbose_name='Avis')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Prestataire')),
            ],
            options={
                'verbose_name': 'Réservation premium',
                'verbose_name_plural': 'Réservations premium',
                'ordering': ['-scheduled_date', '-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='PremiumService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('tutoring', 'Tutorat'), ('mentoring', 'Mentoring'), ('homework_correction', 'Correction de devoirs'), ('career_coaching', 'Coaching de carrière'), ('exam_prep', 'Préparation examen')], max_length=30, verbose_name='Type de service')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('dc_price_per_hour', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Prix par heure (DC)')),
                ('dc_price_per_session', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Prix par session (DC)')),
                ('duration_minutes', models.IntegerField(default=60, verbose_name='Durée (minutes)')),
                ('is_online', models.BooleanField(default=True, verbose_name='En ligne')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Lieu (si présentiel)')),
                ('requirements', models.TextField(blank=True, help_text='Niveau requis, matériel, etc.', verbose_name='Prérequis')),
                ('max_students_per_session', models.IntegerField(default=1, verbose_name='Max étudiants/session')),
                ('available_days', models.JSONField(default=list, help_text="Liste des jours (ex: ['monday', 'wednesday'])", verbose_name='Jours disponibles')),
                ('available_time_start', models.TimeField(verbose_name='Heure début disponibilité')),
                ('available_time_end', models.TimeField(verbose_name='Heure fin disponibilité')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'Actif'), ('paused', 'En pause'), ('inactive', 'Inactif')], default='draft', max_length=20, verbose_name='Statut')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_services', to=settings.AUTH_USER_MODEL, verbose_name='Prestataire')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_services', to='skills.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Service premium',
                'verbose_name_plural': 'Services premium',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PremiumServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Note')),
                ('communication', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Communication')),
                ('expertise', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Expertise')),
                ('helpfulness', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Utilité')),
                ('punctuality', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Ponctualité')),
                ('comment', models.TextField(verbose_name='Commentaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_review', to='premium.premiumbooking', verbose_name='Réservation')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Avisé')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='premium.premiumservice', verbose_name='Service')),
            ],
            options={
                'verbose_name': 'Avis service premium',
                'verbose_name_plural': 'Avis services premium',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='premiumbooking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='premium.premiumservice', verbose_name='Service'),
        ),
        migrations.AddField(
            model_name='premiumbooking',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Étudiant'),
        ),
    ]
