# Generated by Django 4.2 on 2026-07-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('premium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom unique de la fonctionnalité', max_length=100, unique=True, verbose_name='Nom')),
                ('description', models.TextField(help_text='Description de la fonctionnalité', verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, help_text='Cocher pour rendre la fonctionnalité disponible', verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Fonctionnalité premium',
                'verbose_name_plural': 'Fonctionnalités premium',
                'ordering': ['name'],
            },
        ),
    ]
