# Generated by Django 4.2.6 on 2026-05-14 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='badge',
            options={'ordering': ['name'], 'verbose_name': 'Badge', 'verbose_name_plural': 'Badges'},
        ),
        migrations.AlterModelOptions(
            name='userbadge',
            options={'ordering': ['-earned_at'], 'verbose_name': 'Badge utilisateur', 'verbose_name_plural': 'Badges utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='xplog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Journal XP', 'verbose_name_plural': 'Journaux XP'},
        ),
        migrations.AlterField(
            model_name='badge',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='description',
            field=models.TextField(help_text='Description du badge', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='exam_count_threshold',
            field=models.IntegerField(blank=True, help_text="Nombre d'examens requis", null=True, verbose_name="Seuil nombre d'examens"),
        ),
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=models.CharField(blank=True, help_text="Nom de l'icône ou emoji", max_length=50, verbose_name='Icône'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Cocher pour rendre le badge disponible', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='name',
            field=models.CharField(help_text='Nom unique du badge', max_length=100, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='skill_threshold',
            field=models.IntegerField(blank=True, help_text='Pourcentage de compétence requis', null=True, verbose_name='Seuil compétence'),
        ),
        migrations.AlterField(
            model_name='badge',
            name='xp_threshold',
            field=models.IntegerField(blank=True, help_text='XP requis pour obtenir ce badge', null=True, verbose_name='Seuil XP'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='badge',
            field=models.ForeignKey(help_text='Badge obtenu', on_delete=django.db.models.deletion.CASCADE, related_name='user_badges', to='gamification.badge', verbose_name='Badge'),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='earned_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Date à laquelle le badge a été obtenu', verbose_name="Date d'obtention"),
        ),
        migrations.AlterField(
            model_name='userbadge',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='badges', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
        migrations.AlterField(
            model_name='xplog',
            name='action_type',
            field=models.CharField(help_text="Type d'action qui a gagné de l'XP (exam, td, course, etc.)", max_length=50, verbose_name="Type d'action"),
        ),
        migrations.AlterField(
            model_name='xplog',
            name='amount',
            field=models.IntegerField(help_text="Quantité d'XP attribuée", verbose_name='Montant XP'),
        ),
        migrations.AlterField(
            model_name='xplog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date d'attribution"),
        ),
        migrations.AlterField(
            model_name='xplog',
            name='reason',
            field=models.CharField(help_text="Raison de l'attribution de l'XP", max_length=255, verbose_name='Raison'),
        ),
        migrations.AlterField(
            model_name='xplog',
            name='related_course_id',
            field=models.IntegerField(blank=True, help_text='ID du cours associé (si applicable)', null=True, verbose_name='ID cours lié'),
        ),
        migrations.AlterField(
            model_name='xplog',
            name='related_exam_id',
            field=models.IntegerField(blank=True, help_text="ID de l'examen associé (si applicable)", null=True, verbose_name='ID examen lié'),
        ),
        migrations.AlterField(
            model_name='xplog',
            name='related_td_id',
            field=models.IntegerField(blank=True, help_text='ID du TD associé (si applicable)', null=True, verbose_name='ID TD lié'),
        ),
        migrations.AlterField(
            model_name='xplog',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='xp_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
