# Generated by Django 4.2.6 on 2026-06-17 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0002_alter_subject_options_alter_userskill_options_and_more'),
        ('gamification', '0002_alter_badge_options_alter_userbadge_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nom du classement', max_length=255, unique=True, verbose_name='Nom')),
                ('leaderboard_type', models.CharField(choices=[('global_xp', 'XP Global'), ('subject_skill', 'Compétence par Matière'), ('exams_passed', 'Examens Réussis'), ('badges_earned', 'Badges Obtenus'), ('streak', 'Série Consécutive')], help_text='Type de classement', max_length=20, verbose_name='Type de classement')),
                ('description', models.TextField(blank=True, help_text='Description du classement', verbose_name='Description')),
                ('time_period', models.CharField(choices=[('all_time', 'Tout le temps'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('yearly', 'Annuel')], default='all_time', help_text='Période du classement', max_length=20, verbose_name='Période')),
                ('is_active', models.BooleanField(default=True, help_text='Cocher pour rendre le classement visible', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('subject', models.ForeignKey(blank=True, help_text='Matière concernée (pour les classements par compétence)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='skills.subject', verbose_name='Matière')),
            ],
            options={
                'verbose_name': 'Classement',
                'verbose_name_plural': 'Classements',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(help_text='Position dans le classement', verbose_name='Position')),
                ('score', models.IntegerField(default=0, help_text="Score de l'utilisateur", verbose_name='Score')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('leaderboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='gamification.leaderboard', verbose_name='Classement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Entrée de classement',
                'verbose_name_plural': 'Entrées de classement',
                'ordering': ['position'],
                'unique_together': {('leaderboard', 'user')},
            },
        ),
    ]
