# Generated by Django 4.2.6 on 2026-06-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0003_leaderboard_leaderboardentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='icon_image',
            field=models.ImageField(blank=True, help_text="Image personnalisée pour l'icône du badge", null=True, upload_to='badge_icons/', verbose_name="Image de l'icône"),
        ),
        migrations.AddField(
            model_name='badge',
            name='use_image',
            field=models.BooleanField(default=False, help_text="Cocher pour utiliser l'image au lieu de l'icône", verbose_name="Utiliser l'image"),
        ),
    ]
