# Generated by Django 4.2 on 2026-07-05 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0004_badge_icon_image_badge_use_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement', models.CharField(help_text='Nom de la réalisation', max_length=100, verbose_name='Réalisation')),
                ('description', models.TextField(blank=True, help_text='Description de la réalisation', verbose_name='Description')),
                ('earned_at', models.DateTimeField(auto_now_add=True, help_text='Date à laquelle la réalisation a été obtenue', verbose_name="Date d'obtention")),
                ('user', models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Réalisation utilisateur',
                'verbose_name_plural': 'Réalisations utilisateurs',
                'ordering': ['-earned_at'],
            },
        ),
    ]
