# Generated by Django 4.2.6 on 2026-05-14 20:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('review', 'Review - Suggest revision for weak areas'), ('advance', 'Advance - Suggest harder content for strong areas'), ('practice', 'Practice - Suggest TD for skill improvement'), ('learn', 'Learn - Suggest courses for new topics')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('context', models.JSONField(blank=True, default=dict)),
                ('priority', models.IntegerField(default=5, help_text='1-10, higher is more important')),
                ('is_active', models.BooleanField(default=True)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('suggested_exam_id', models.IntegerField(blank=True, null=True)),
                ('suggested_course_id', models.IntegerField(blank=True, null=True)),
                ('suggested_td_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
