# Generated by Django 4.2.6 on 2026-05-14 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recommendation',
            options={'ordering': ['-priority', '-created_at'], 'verbose_name': 'Recommandation', 'verbose_name_plural': 'Recommandations'},
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='context',
            field=models.JSONField(blank=True, default=dict, help_text='Données contextuelles (JSON) comme matière, score, etc.', verbose_name='Contexte'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.TextField(help_text='Description détaillée de la recommandation', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Indique si la recommandation est active', verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='is_dismissed',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a ignoré la recommandation", verbose_name='Ignoré'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='priority',
            field=models.IntegerField(default=5, help_text='1-10, plus élevé = plus important', verbose_name='Priorité'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='recommendation_type',
            field=models.CharField(choices=[('review', 'Réviser - Suggérer la révision pour les domaines faibles'), ('advance', 'Avancer - Suggérer du contenu plus difficile pour les domaines forts'), ('practice', "Pratiquer - Suggérer des TD pour l'amélioration des compétences"), ('learn', 'Apprendre - Suggérer des cours pour de nouveaux sujets')], help_text='Type de recommandation généré', max_length=20, verbose_name='Type de recommandation'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='suggested_course_id',
            field=models.IntegerField(blank=True, help_text='ID du cours suggéré (si applicable)', null=True, verbose_name='ID cours suggéré'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='suggested_exam_id',
            field=models.IntegerField(blank=True, help_text="ID de l'examen suggéré (si applicable)", null=True, verbose_name='ID examen suggéré'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='suggested_td_id',
            field=models.IntegerField(blank=True, help_text='ID du TD suggéré (si applicable)', null=True, verbose_name='ID TD suggéré'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='title',
            field=models.CharField(help_text='Titre de la recommandation', max_length=255, verbose_name='Titre'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='user',
            field=models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur'),
        ),
    ]
