# Generated by Django 4.2 on 2026-07-05 08:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0004_skill'),
        ('recommendations', '0002_alter_recommendation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(help_text='Description de la recommandation', verbose_name='Recommandation')),
                ('priority', models.IntegerField(default=5, help_text='1-10, plus élevé = plus important', verbose_name='Priorité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('skill', models.ForeignKey(help_text='Compétence concernée', on_delete=django.db.models.deletion.CASCADE, related_name='skill_recommendations', to='skills.skill', verbose_name='Compétence')),
                ('user', models.ForeignKey(help_text='Utilisateur concerné', on_delete=django.db.models.deletion.CASCADE, related_name='skill_recommendations', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Recommandation de compétence',
                'verbose_name_plural': 'Recommandations de compétences',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
